phases:
build:
  commands:
    - echo Building...
    - mvn clean package
post_build:
    commands:
      - echo Build completed on successfully `date` 
artifacts:
  files:
    - target/springbootdemo-0.0.1-SNAPSHOT.jar
discard-paths: yes
