phases:
  build:
   commands:
	 - echo Entered the build phases
	 - mvn clean package
  post_build:
	commands:
	 - echo build completed successfully
artifacts:
	files:
	  - target/springbootdemo-0.0.1-SNAPSHOT.jar
	discard-paths: yes